### ISSUE TITLE
Crashes on start, Android 4.3 (BB10)

### ISSUE THREAD

**Issue by johnb-xp** [Rudloff/hangupsdroid#12] opened 2019-02-09 23:39 UTC
Not sure if you'd be interested in working on this issue, lol.

Downloaded the apk of Version 0.1.0 on my BlackBerry Classic, it installed but crashes instantly when I open the app.
The BlackBerry 10 Android Runtime is pretty reliable, so there may be an issue with running the app on Android 4.3. Still, the crashing could be specific to BB10.

I'd be happy to provide more details.

**Comment by Rudloff** [comment] 2019-02-11 12:41
Hello,
I can't reproduce the crash on Android 4.2.2 so this might be specific to BlackBerry.
Would it be possible to provide logs so I can see what happens when it crashes?

**Comment by johnb-xp** [comment] 2019-02-11 20:46
Sure, where would the logs be stored?

**Comment by Rudloff** [comment] 2019-02-12 09:31
On Android, we use [logcat](https://developer.android.com/studio/command-line/logcat).
According to [this article](http://devblog.blackberry.com/2013/11/pull-android-logs-from-your-blackberry/), it would be possible to use it on Blackberry, but it might be a bit more complicated.

You could also wait for https://github.com/Rudloff/hangupsdroid/issues/11 to be fixed so I can receive crash reports automatically.

**Comment by johnb-xp** [comment] 2019-02-13 23:55
I've been trying my best to get adb working, can't get it to connect. I started a thread in the BlackBerry Developer forums, but it looks like I'll have to wait for #11 to be fixed. I'm worried the automatic crash reporting wouldn't work because the app crashes instantly.

**Comment by Rudloff** [comment] 2019-02-19 21:50
I published [a new release](https://github.com/Rudloff/hangupsdroid/releases/tag/0.1.1) that includes a crash reporter, if you want to try.
(However, I have no idea if it is compatible with the BlackBerry runtime or if it will work if the app crashes before it is loaded.)

**Comment by johnb-xp** [comment] 2019-02-20 00:06
The new apk fails to install on my BlackBerry, but installs on another Android device.

**Comment by Rudloff** [comment] 2019-02-20 09:07
That is strange. Do you get an error when you try to install it?

**Comment by johnb-xp** [comment] 2019-02-20 23:25
![img_20190220_143429](https://user-images.githubusercontent.com/47438957/53132130-645e8b80-3534-11e9-9465-40bff2fda98a.png)

This is what I get when I install the newest APK. Previous version did install but wouldn't run.

**Comment by Rudloff** [comment] 2019-02-24 22:22
There was a signing issue with the 0.1.1 APK (https://github.com/Rudloff/hangupsdroid/issues/15).
I reuploaded it, can you try installing again?

**Comment by johnb-xp** [comment] 2019-02-26 14:47
Latest version installs, shows a white screen, then crashes. Does not crash before opening now.

**Comment by Rudloff** [comment] 2019-02-26 15:23
And it did not ask if you wanted to send a crash report via e-mail?
Then it probably means that the Acra crash reporter does not work on BB10 :slightly_frowning_face:

**Comment by Rudloff** [comment] 2019-04-10 21:45
Closing since it seems there is nothing I can do :slightly_frowning_face:

**Closed as completed by Rudloff** 2019-04-10 21:45 UTC
